### ISSUE TITLE
Error while creating channel

### ISSUE THREAD

**Issue by syaau** [sharingapples/shocked#12]
(node:29168) UnhandledPromiseRejectionWarning: Error: Channel instance with the same id is already registered todo-1
    at Instance.subscribe (/Users/ranjanshrestha/Workspace/SharingApples/shocked/packages/server/src/DefaultChannelDriver.js:40:17)
    at UserTracker.start (/Users/ranjanshrestha/Workspace/SharingApples/shocked/packages/server/src/Tracker.js:16:21)
    at TodoService.createTracker (/Users/ranjanshrestha/Workspace/SharingApples/shocked/packages/server/src/Service.js:115:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:29168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by syaau** [comment]
Fixed by https://github.com/sharingapples/shocked/commit/536db92083d9681aebe19f4476b2f374fb9ebc1d
